version: '3.1'
services:
  db:
    image: postgres:16-alpine
    container_name: weshare_db
    environment:
      POSTGRES_DB: weshare
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./server/src/main/resources/db/create-test-data.sql:/create-test-data.sql

volumes:
  postgres-data:
