name: PROD-Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_CONNECTION: ${{ secrets.SSH_CONNECTION }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SERVER_COMMANDS: ${{ secrets.PROD_SERVER_COMMANDS }}

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build project with Maven
        run: mvn clean package -DskipTests -f server/pom.xml

      - name: Deploy to Server
        run: |
          echo "Deploying JAR to VM"
          scp server/target/*.jar $SSH_CONNECTION:$DEPLOY_PATH
          ssh $SSH_CONNECTION << EOF
          $SERVER_COMMANDS
          EOF
